apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-backup-api
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - rbac.yaml
  - secrets.yaml
