---
# Source: langflow-ide/templates/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow-service-frontend
  labels:
    app: langflow-service
    chart: langflow-ide-0.1.1
    release: langflow-ide
    langflow-scope: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow-service
      chart: langflow-ide-0.1.1
      release: langflow-ide
      langflow-scope: "frontend"
  template:
    metadata:
      labels:
        app: langflow-service
        chart: langflow-ide-0.1.1
        release: langflow-ide
        langflow-scope: "frontend"
    spec:
      serviceAccountName: langflow-service
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      volumes:
        - emptyDir: {}
          name: tmp
        - name: nginx
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
      containers:
        - name: langflow-ide
          image: "langflowai/langflow-frontend:1.6.9"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /tmp
              name: tmp
              readOnly: false

            - name: nginx
              mountPath: "/tmp/nginx"
              readOnly: false
            - name: nginx-cache
              mountPath: "/var/cache/nginx"
              readOnly: false
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3   
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3   
          env:
            - name: BACKEND_URL
              value: "http://langflow-service-backend.langflow.svc.cluster.local:7860"
            - name: FRONTEND_PORT
              value: "8080"
