# minha-app/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: langflow
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - network-policy.yaml
  - pod-disruption-budget.yaml
  - secret.yaml
  - service-account.yaml
  - service.yaml
  - statefulset.yaml
