---
# Source: langflow-ide/charts/postgresql/templates/primary/svc-headless.yaml
apiVersion: v1
kind: Service
metadata:
  name: langflow-ide-postgresql-hl
  namespace: "langflow"
  labels:
    app.kubernetes.io/instance: langflow-ide
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.38
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  # We want all pods in the StatefulSet to have their addresses published for
  # the sake of the other Postgresql pods even before they're ready, since they
  # have to be able to talk to each other in order to become ready.
  publishNotReadyAddresses: true
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: langflow-ide
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: langflow-ide/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: langflow-ide-postgresql
  namespace: "langflow"
  labels:
    app.kubernetes.io/instance: langflow-ide
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 16.4.0
    helm.sh/chart: postgresql-15.5.38
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/instance: langflow-ide
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
---
# Source: langflow-ide/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: langflow-service
  labels:
    app: langflow-service
    chart: langflow-ide-0.1.1
    release: langflow-ide
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: langflow-service
    chart: langflow-ide-0.1.1
    release: langflow-ide
    langflow-scope: "frontend"
---
# Source: langflow-ide/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: langflow-service-backend
  labels:
    app: langflow-service
    chart: langflow-ide-0.1.1
    release: langflow-ide
spec:
  type: ClusterIP
  ports:
    - port: 7860
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: langflow-service
    chart: langflow-ide-0.1.1
    release: langflow-ide
    langflow-scope: "backend"
