# minha-app/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - configmap.yaml
  - crd.yaml
  - deployment.yaml
  - ingress-class.yaml
  - namespace.yaml
  - service-account.yaml
  - service.yaml

