apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: nexus-api-teste

resources:
- ../../../../bases/nexus-api/1.0.0

patches:
- path: ingress.yaml
- path: secret.yaml
- path: deployment.yaml
#- path: deployment.yaml
