# minha-app/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - crd.yaml
  - deployment.yaml
  - mutating-webhook-configuration.yaml
  - namespace.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - service.yaml
  - validating-webhook-configuration.yaml
