apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-backup-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-backup-webapp
  template:
    metadata:
      labels:
        app: nexus-backup-webapp
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nexus-backup-webapp
          image: ghcr.io/synapsehealthtech/nexus-backup-webapp:v0.0.4
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: nexus-backup-webapp-config
