apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-backup-webapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: backup.nexusplatform.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-backup-webapp
                port:
                  number: 80
