apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-adm-webapp-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  # O bloco TLS fica aqui, na raiz de 'spec'
  tls:
  - hosts:
    - console.nexusplatform.com.br
    secretName: console-tls-secret
  
  rules:
  - host: console.nexusplatform.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nexus-adm-webapp-service
            port:
              number: 80