---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-webapp-deployment
spec:
  selector:
    matchLabels:
      app: nexus-webapp
  template:
    metadata:
      labels:
        app: nexus-webapp
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: nexus-webapp-container
        image: ghcr.io/synapsehealthtech/nexus-webapp:v0.1.17
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: cloudflare-front-credentials
        command: ["/bin/sh", "-c"]
        args:
          - >-
            echo "window.env = { VITE_CLOUDFLARE_SITE_KEY: '$VITE_CLOUDFLARE_SITE_KEY' };" > /usr/share/nginx/html/config.js &&
            nginx -g 'daemon off;'
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
        # "volumeMounts" está no lugar certo, dentro de "containers"
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          
      # --- SEÇÃO CORRIGIDA ---
      # "volumes" foi movido para fora de "containers" e agora está
      # no mesmo nível, diretamente sob "spec".
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nexus-webapp-nginx-conf
