apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: nexus-webapp-teste

resources:
- ../../../../bases/nexus-webapp/1.0.0
patches:
- path: secret.yaml
- path: ingress.yaml
- path: deployment.yaml
#- path: service.yaml
