apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: nexus-api-amable

resources:
- ../../../../bases/nexus-api/1.0.0
#- secret.yaml
patches:
- path: secret.yaml
- path: deployment.yaml
- path: ingress.yaml
