---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-config
  namespace: nexus-backup
data:
  BACKUP_DB_USER: "backup_operator"
  OCI_BUCKET_NAME: "nexus-backup"
  OCI_CONFIG_PROFILE: "DEFAULT"
  MAX_WORKERS: "1"
  NAMESPACE_API_PREFIX: "nexus-api-"
  NAMESPACE_WEB_PREFIX: "nexus-webapp-"
  TENANT_SECRET_NAME: "nexus-db-credentials"
  TENANT_SECRET_KEY: "DATABASE_URL"
