apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: nexus-cep

resources:
- ../../../bases/nexus-cep/1.0.0

patches:
- path: secret.yaml
- path: deployment.yaml
#- path: deployment.yaml
